### PR TITLE
fix: Fix `CosmosCheckboxTile` for dark/light themes

### LINKED ISSUE #272: [Bug] `CosmosCheckboxTile` doesn't have proper check/unchecked icons on dark/light themes
Light theme is good:
Screenshot 2022-05-10 at 6 59 35 PM
Screenshot 2022-05-10 at 6 59 31 PM

Dark theme is not:
Screenshot 2022-05-10 at 6 59 53 PM
Screenshot 2022-05-10 at 6 59 57 PM

Solution:
Place only the inner check as assets (not the whole filled image) and give it color from `CosmosTheme`

### PR DESCRIPTION
**Pull request by wal33d006**
Closes #272 
Looks like this -->

Light:
Screenshot 2022-05-10 at 7 49 42 PM
Screenshot 2022-05-10 at 7 49 47 PM

Dark:
Screenshot 2022-05-10 at 7 49 19 PM
Screenshot 2022-05-10 at 7 49 23 PM

### CODE REVIEW

File: packages/cosmos_ui_components/lib/components/cosmos_checkbox_tile.dart [hunk 1]
```diff
@@ -43,8 +43,9 @@ class CosmosCheckboxTile extends StatelessWidget {
                     right: theme.spacingL,
                   ),
                   child: Image.asset(
-                    "assets/images/checkbox_${checked ? "checked" : "unchecked"}.png",
+                    'assets/images/checkbox${checked ? "" : "_unchecked"}.png',
```
Comment (andrzejchm) [inline packages/cosmos_ui_components/lib/components/cosmos_checkbox_tile.dart:46]: since you got rid of `checkbox_checked.png` from code, lets clean up the assets too, or, simply rename the files you've added from `checkbox.png` to `checkbox_checked.png`

**Review by andrzejchm — CHANGES_REQUESTED** [review]

**Comment by wal33d006** [comment]
> now, we have 2x `checkbox.png` and 3x `checkbox_checked.png`

My bad, I thought it renamed in all folders. Just fixed it.

**Review by andrzejchm — APPROVED** [review]
🚢 it!
