### PR TITLE
fix: (transaction) 🐛 fixed amount denom

### LINKED ISSUE #212: Change denom on the "Transferred!" page
**Desription**
Currently, the denom is hard-coded to `AKT`. Notice the same thing happens when the transaction is being transferred (the modal with a spinner).

**Expected behavior**
The denom should correspond to the one being sent.

Screenshot 2022-02-16 at 11 15 33

### PR DESCRIPTION
**Pull request by Zfinix**
Fixes #212

### CODE REVIEW

**Comment by Zfinix** [comment]
> Fixes #212
Simulator Screen Shot - iPhone 13 Pro Max - 2022-02-25 at 16 22 18

File: starport_template/lib/pages/assets_transfer_sheet.dart [hunk 1]
```diff
@@ -41,24 +47,43 @@ class _AssetsTransferSheetState extends State<AssetsTransferSheet> {
...
+                      height: 56,
+                      width: 56,
+                      child: Image.asset('assets/images/check_circle.png'),
+                    ),
                     SizedBox(height: theme.spacingXL),
                     Text('Transferred!', style: CosmosTextTheme.title2Bold),
                     const Spacer(),
-                    Text('1134.48 AKT', style: CosmosTextTheme.title0Medium),
+                    Text(
+                      '${widget.balance.amount.value.toDouble()} '
```
Comment (andrzejchm) [inline starport_template/lib/pages/assets_transfer_sheet.dart:82]: same here

File: starport_template/lib/pages/assets_transfer_sheet.dart [hunk 2]
```diff
@@ -41,24 +47,43 @@ class _AssetsTransferSheetState extends State<AssetsTransferSheet> {
...
+                  Text(
+                    'This may take up to 1 minute.',
+                    style: CosmosTextTheme.copy0Normal,
+                  ),
                   const Spacer(),
                   const ContentLoadingIndicator(),
                   const Spacer(),
-                  Text('1134.48 AKT', style: CosmosTextTheme.title0Medium),
+                  Text(
+                    '${formatAmount(widget.balance.amount.value.toDouble(), symbol: '')} ${widget.balance.denom}'
```
Comment (andrzejchm) [inline starport_template/lib/pages/assets_transfer_sheet.dart:58]: we're loosing precision here, there is a reason why we went with `Decimal` objects instead of simply doubles. 

Here's short explanation: https://stackoverflow.com/a/3730040

you could try with:

```suggestion
                      '${widget.balance.amount.value.toString()}'
```
but if you need to control the precision, you can use `toStringAsPrecision()` then

cc: @wal33d006

File: starport_template/lib/pages/routing_page.dart [hunk 3]
```diff
@@ -22,7 +22,6 @@ class _RoutingPageState extends State<RoutingPage> {
   void initState() {
     super.initState();
     initialize();
-    _loadWallets();
```
Comment (andrzejchm) [inline starport_template/lib/pages/routing_page.dart:25]: are we sure we want to stop loading wallets on the app start?

File: starport_template/lib/pages/sign_transaction_page.dart [hunk 4]
```diff
@@ -124,10 +125,14 @@ class _SignTransactionPageState extends State<SignTransactionPage> {
...
     showMaterialModalBottomSheet(
       context: context,
+      isDismissible: false, // Stop user from tapping outside sheet to dismiss
       backgroundColor: Colors.transparent,
       builder: (context) => SizedBox(
         height: MediaQuery.of(context).size.height / 2.24,
         child: AssetsTransferSheet(
+          balance: widget.balance.copyWith(
+            amount: Amount.fromDouble(recipientGetsAmount),
+          ),
```
Comment (andrzejchm) [inline starport_template/lib/pages/sign_transaction_page.dart:135]: let's not manipulate data inside the widget's tree. You can create a getter for the `reicipientGetsAmount` balance:

```dart
Balance get recipientGetsAmountBalance => widget.balance.copyWith(
            amount: Amount.fromDouble(recipientGetsAmount),
          );
```

File: starport_template/lib/pages/assets_transfer_sheet.dart [hunk 5]
```diff
@@ -1,25 +1,31 @@
...
 
 class AssetsTransferSheet extends StatefulWidget {
   const AssetsTransferSheet({
     required this.onTapDone,
+    required this.balance,
     Key? key,
   }) : super(key: key);
 
   final VoidCallback onTapDone;
+  final Balance balance;
```
Comment (andrzejchm) [inline starport_template/lib/pages/assets_transfer_sheet.dart:18]: the name is a bit too ambiguous. how about:

```dart
final Balance recipientGetsAmountBalance
```

**Review by andrzejchm — CHANGES_REQUESTED** [review]
solid work! I've left few changes proposals with explanation, if you have any questions, just drop me a message!

File: starport_template/lib/pages/sign_transaction_page.dart (hunk 4 above)
Comment (wal33d006) [reply starport_template/lib/pages/sign_transaction_page.dart:135]: Here we are using the `fromDouble` constructor for `Amount` which we shouldn't. The `recipientGetsAmount` is a decimal value coming from this line somewhere above this file
`double get recipientGetsAmount => widget.transaction.amount.value.toDouble() - widget.transaction.fee;`

Technically this manipulation shouldn't be inside the UI and secondly this `widget.transaction.fee` should be a type of `Amount` as well so that we can add/subtract within decimals. What do you think @andrzejchm ?

File: starport_template/lib/entities/amount.dart [hunk 6]
```diff
@@ -19,6 +20,6 @@ extension StringAmount on String {
   Amount get amount => Amount.fromString(this);
 }
 
-extension IntAmount on int {
-  Amount get amount => Amount.fromInt(this);
+extension NumAmount on num {
```
[the remark this answers is not in the document]
Comment (Zfinix) [reply starport_template/lib/entities/amount.dart:23]: You are right.

File: starport_template/lib/pages/sign_transaction_page.dart (hunk 4 above)
Comment (andrzejchm) [reply starport_template/lib/pages/sign_transaction_page.dart:135]: good catch @wal33d006 ! definetely we should stick with `Amount/Decimal` and not convert back and forth from/to doubles

File: starport_template/lib/pages/routing_page.dart (hunk 3 above)
Comment (Zfinix) [reply starport_template/lib/pages/routing_page.dart:25]: Yes i discovered this s the cause of multiple account balances being loaded we already call `_loadWallets()` in `initialize()`

File: starport_template/lib/pages/assets_transfer_sheet.dart [hunk 7]
```diff
@@ -41,24 +46,43 @@ class _AssetsTransferSheetState extends State<AssetsTransferSheet> {
...
+                      height: 56,
+                      width: 56,
+                      child: Image.asset('assets/images/check_circle.png'),
+                    ),
                     SizedBox(height: theme.spacingXL),
                     Text('Transferred!', style: CosmosTextTheme.title2Bold),
                     const Spacer(),
-                    Text('1134.48 AKT', style: CosmosTextTheme.title0Medium),
+                    Text(
+                      '${widget.recipientGetsAmountBalance.amount.value.toDouble()} '
```
Comment (wal33d006) [inline starport_template/lib/pages/assets_transfer_sheet.dart:81]: `formatAmount(widget.recipientGetsAmountBalance.amount.value.toDouble())`

**Comment by wal33d006** [comment]
Looks amazing! Let Andrzej have a look and we are good to go!

**Review by andrzejchm — APPROVED** [review]
awesome work!
